### ISSUE TITLE
I don't understand

### ISSUE THREAD

**Issue by profesionalleet1337** [samay825/Sutra-Spoof#1]
I can't try this tool, and can't understand this is a paid or free instrument?
When I tried to use it, it say's me : └─ Not Verified !! Please Buy the script from samay825 or Linuxndroid Instagram | @sincryptasur >>><<< Telegram | @sincryptzork
So, this is no free option for try or what ?

**Comment by profesionalleet1337** [comment]
@samay825 , could u answear me?

**Comment by samay825** [comment]
dm me in telegram sincryptzork
